const data = [
    {
        id: "nk01",
        modelo: "phantom gt",
        precio: 50000,
        stock: 5,
        img: "phantom-gt-nk.webp",
        descripcion: "Bota de fútbol Nike Phantom GT2 Elite DF SG Pro-Ac para adultos. Bota de hilo con calcetín, para utilizar en campos de hierba natural húmeda o mojada. Botas de gama alta para jugadores de control y precisión en color Metallic Copper-White-Black.",
        categoria: "botines",
        subcategoria: "nike"
    },
    {
        id: "nk02",
        modelo: "tiempo legend",
        precio: 45000,
        stock: 0,
        img: "timepo-legend-nk.webp",
        descripcion: "Bota de fútbol Nike Tiempo Legend 9 Elite SG-Pro Ac para adultos. Botas de piel, para utilizar en campos de hierba natural húmeda o mojada. Botas de gama alta en color  Space Purple-White.",
        categoria: "botines",
        subcategoria: "nike",
    },
    {
        id: "nk03",
        modelo: "mercurial",
        precio: 75000,
        stock: 3,
        img: "mercurial-nk.webp",
        descripcion: "Bota de fútbol Nike Zoom Vapor 15 Elite FG para adultos. Botas de hilo, sin calcetín para utilizar en campos de hierba natural seca o húmeda. Botas de gama alta en color Metallic Cooper",
        categoria: "botines",
        subcategoria: "nike",
    },
    {
        id: "ad01",
        modelo: "predator",
        precio: 36000,
        stock: 6,
        img: "predator-ad.webp",
        descripcion: "Se acerca la Copa del Mundo de Qatar y adidas nos presenta la colección que lucirán sus jugadores durante el torneo más importante del año. Multitud de colores en una colección asociada a la decoración del balón con el que se jugará el Mundial.",
        categoria: "botines",
        subcategoria: "adidas",
    },
    {
        id: "ad02",
        modelo: "copa",
        precio: 25000,
        stock: 5,
        img: "copa-ad.webp",
        descripcion: "Bota de fútbol adidas Copa Pure +FG para adultos. Botas de piel con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Core Black-Zero Metallic-Shock Pink para jugadores clásicos.",
        categoria: "botines",
        subcategoria: "adidas",
    },
    {
        id: "ad03",
        modelo: "x speedflow",
        precio: 75000,
        stock: 16,
        img: "x-speedflow-ad.jpeg",
        descripcion: "Solo los mejores pueden llevar los botines adidas dorados en el torneo más prestigioso de fútbol de selecciones. Estos botines especiales X Speedportal rinden homenaje al brillante legado de Leo Messi, que tratará de hacerse con la victoria en su cita en Catar. Inspirada en los detalles de los botines que llevó en su debut mundialista en 2006, la parte superior de tejido adidas PRIMEKNIT se adapta al pie y destaca gracias a su diseño dorado. La ligera suela Speedframe incluye una inserción de fibra de carbono Carbitex que le ayudará a conseguir el tercer campeonato mundial para su país.",
        categoria: "botines",
        subcategoria: "adidas",
    },
    {
        id:"nk04",
        modelo: "chelsea 23",
        precio: 16000,
        stock: 6,
        img: "chelsea-23-nk.jpg",
        descripcion: "Camiseta primera equipación Chelsea 2022-2023, al igual que otras  de la colección Match, esta combina detalles auténticos de diseño con un tejido ligero y de secado rápido para que las mejores estrellas del fútbol del mundo disfruten de una gran frescura y comodidad en el campo. Este producto está fabricado con fibras de poliéster 100 % reciclado.",
        categoria: "camisetas",
        subcategoria: "nike",
    },
    {
        id:"ad04",
        modelo: "manchester united 23",
        precio: 16000,
        stock: 5,
        img: "manchester-united-23-ad.webp",
        descripcion: "Camiseta authentic de la primera equipación Manchester United, temporada 2022/2023. Cuenta con cuello estilo polo, el cual ha sido testigo de algunos de los momentos más importantes de la historia del equipo. Esta camiseta de fútbol adidas recupera este emblemático símbolo y lo combina con un nuevo escudo y un llamativo estampado de rayas finas. Se ha confeccionado en tejido transpirable AEROREADY con paneles de malla para ofrecerte la comodidad que necesitas desde las gradas.",
        categoria: "camisetas",
        subcategoria: "adidas",
    },
    {
        id:"nk05",
        modelo: "premier league 23",
        precio: 25000,
        stock: 10,
        img: "premier-league-23-nk.webp",
        descripcion: "Perfeccionado durante 8 años y 1700 horas de pruebas, el balón de fútbol Nike Flight es una revolución en el vuelo constante. Los surcos moldeados y una textura adherente reducen el movimiento inesperado en el aire para ayudarte a poner la pelota donde quieras.",
        categoria: "pelotas",
        subcategoria: "nike",
    },
    {
        id: "ad05",
        modelo: "champions league 23",
        precio: 25000,
        stock: 50,
        img: "champions-league-23-ad.webp",
        descripcion: "¡Por fin! En 2023 las estrellas se alinean en Estambul. Creado para la fase eliminatoria de la UEFA Champions League, este balón adidas luce un llamativo estampado que rinde homenaje a la ubicación única de la ciudad y a su relación con la mayor competición de clubes de fútbol del mundo. La superficie sin costuras con sello de calidad FIFA Quality Pro y la cámara de butilo te garantizan un rendimiento óptimo en el terreno de juego.",
        categoria: "pelotas",
        subcategoria: "adidas",
    },
]

export default data